Repository AY2425S1-CS2103-F13-3/tp, pull requests merged in 2024-11, with the labels that each got.

#125 Fix sample schedule list implementation behvaiour
  docs/DeveloperGuide.md
  docs/diagrams/LoadScheduleActivityDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug

#128 Update command summary and help window and add `meeting-contacts` in UG
  docs/UserGuide.md
  docs/images/meeting-contacts_example.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Chore

#127 Test coverage for Meeting stuff, remove unused code
  src/main/java/seedu/address/model/schedule/Meeting.java
  src/main/java/seedu/address/model/schedule/UniqueMeetingList.java
  src/main/java/seedu/address/storage/JsonSerializedScheduleStorage.java
  src/test/data/JsonSerializableScheduleStorageTest/duplicateMeetingsSchedule.json
  src/test/data/JsonSerializableScheduleStorageTest/invalidEntriesMeetingsSchedule.json
  src/test/data/JsonSerializableScheduleStorageTest/typicalMeetingsSchedule.json
  src/test/java/seedu/address/model/ScheduleListTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/schedule/MeetingTest.java
  src/test/java/seedu/address/model/schedule/SameWeekAsDatePredicateTest.java
  src/test/java/seedu/address/model/schedule/UniqueMeetingListTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableScheduleStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Chore

#140 Fix `see` command not catching datetimeparse exceptions
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SeeScheduleCommand.java
  src/main/java/seedu/address/logic/parser/SeeScheduleCommandParser.java
Labels: type.Bug, severity.Medium, alpha-bug

#137 Update UML Diagrams and DG for delete schedule and UI
  docs/DeveloperGuide.md
  docs/diagrams/DeleteScheduleSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Chore, priority.Medium

#146 Add ignore ui codecov
  codecov.yml
Labels: type.Chore

#145 Test coverage for seeschedule, seeallschedule, and addressbookparser
  src/main/java/seedu/address/logic/commands/SeeAllScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SeeScheduleCommand.java
  src/test/java/seedu/address/logic/commands/SeeAllScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/SeeScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SeeScheduleCommandParserTest.java
Labels: type.Chore

#149 Fix edit schedule duplicate bug
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.Bug, alpha-bug

#141 Add Edit schedule to DG
  docs/DeveloperGuide.md
Labels: type.Chore

#156 Unit Testing for Delete Schedule Command and Delete Schedule Command Parser
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SeeAllScheduleCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteScheduleCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Chore, priority.Medium

#153 Fix alpha-bug issues related to add-schedule
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/Meeting.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/model/schedule/MeetingTest.java
Labels: alpha-bug

#161 [UG] Add Favourite Contact and Update Example Images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/add-schedule_example.png
  docs/images/helpMessage.png
  docs/images/meeting-contacts_example.png
Labels: type.Chore, priority.Medium

#154 Test coverage for jsonschedulestorage and storagemanager
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonScheduleStorageTest/invalidEntriesMeetingsSchedule.json
  src/test/data/JsonScheduleStorageTest/notJsonFormatSchedule.json
  src/test/java/seedu/address/storage/JsonScheduleStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Chore

#165 Update DG title
  docs/DeveloperGuide.md
Labels: alpha-bug

#163 Fix test cases due to meeting conflict conditions changing
  src/test/java/seedu/address/storage/JsonScheduleStorageTest.java
Labels: type.Chore, type.Bug, priority.High

#151 UI Enhancement and Minor Bug Fix
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/calendar/CalendarCard.java
  src/main/java/seedu/address/ui/calendar/DailySchedulePanel.java
  src/main/java/seedu/address/ui/calendar/WeeklySchedulePanel.java
  src/main/resources/view/CalendarListCard.fxml
  src/main/resources/view/CalendarStyle.css
  src/main/resources/view/DailyCalendarPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/WeeklyCalendarPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium, alpha-bug

#170 Fix wildcard import
  src/main/resources/view/PersonListCard.fxml
Labels: type.Chore

#171 Update DG diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MeetingContactsSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Chore

#178 Test coverage for multiple more classes
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/logic/parser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Chore

#260 Add error message edit schedule when contact list is empty
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
Labels: severity.Low

#269 Update Non's Portfolio
  docs/team/tata32000.md
Labels: type.Chore

#270 Update documentation of UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jewiteo.md
Labels: type.Bug, priority.Low, severity.Medium

#268 UI bug fix for commands not correctly updating index and details
  src/main/java/seedu/address/model/schedule/SameWeekAsDatePredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/WeeklySchedulePanel.java
  src/test/java/seedu/address/model/schedule/SameWeekAsDatePredicateTest.java
Labels: type.Bug, severity.Medium, alpha-bug

#271 Update clear command description in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#272 Fix edit schedule command parser exception
  src/main/java/seedu/address/logic/parser/EditScheduleCommandParser.java
Labels: type.Bug
