Repository AY2425S1-CS2103-F13-3/tp, pull requests merged in 2024-10, with the labels that each got.

#53 Modify format of find command to use prefix
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#61 v1.3 - Add GUI and implement See Schedule Command
  .gitignore
  schedule.json
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SeeAllScheduleCommand.java
  src/main/java/seedu/address/logic/commands/SeeScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SeeScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/schedule/SameWeekAsDatePredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/CalendarCard.java
  src/main/java/seedu/address/ui/calendar/WeeklySchedulePanel.java
  src/main/resources/view/CalendarListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/WeeklyCalendarPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#57 v1.3 - Revamp predicate and add find parameter
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/FieldContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Enhancement, priority.Medium

#63 Fix see command throwing errors
  schedule.json
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SeeScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/SeeScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/SameWeekAsDatePredicate.java
Labels: type.Bug, severity.High

#68 v1.2 Add Delete Schedule Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteScheduleCommandParser.java
Labels: type.Story, priority.Medium

#69 Update user guide with new commands
  docs/UserGuide.md
  docs/images/findAlexclassmatesResult.png
Labels: type.Chore

#74 1.3 fix edit schedule message usage
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
Labels: type.Bug, severity.Low

#79 UID for Person
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/schedule/Meeting.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/calendar/CalendarCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High

#83 delete command to check if contact exist in schedue
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ScheduleList.java
  src/main/java/seedu/address/model/schedule/Meeting.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, priority.High, severity.High

#85 Fix: Edit Schedule throw exception and fix optional fields
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/EditScheduleCommandParser.java
  src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium

#89 Implement `meeting-contacts` command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MeetingContactsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MeetingContactsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/FieldContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#92 Enable assertions in build file
  build.gradle
Labels: type.Chore

#91 Enhance file error detection and handling
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonScheduleStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleStorage.java
  src/main/java/seedu/address/storage/ScheduleStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug, severity.Medium

#94 Update docs include UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/MeetingContactsSequenceDiagram.puml
Labels: type.Chore, priority.Low

#97 Implement sample data for schedule for new users
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement, priority.Low

#98 Implement Daily Schedule List
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/calendar/CalendarCard.java
  src/main/java/seedu/address/ui/calendar/DailySchedulePanel.java
  src/main/java/seedu/address/ui/calendar/WeeklySchedulePanel.java
  src/main/resources/view/DailyCalendarPanel.fxml
  src/main/resources/view/WeeklyCalendarPanel.fxml
Labels: type.Enhancement, priority.Medium

#95 Add schedule commands into help command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: severity.Medium

#108 Update user guide link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Chore

#107 Add edit schedule sequence diagram
  docs/diagrams/EditScheduleSequenceDiagram.puml
Labels: type.Chore

#102 Fix Edit Schedule to support contact deletion
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/Meeting.java
  src/test/java/seedu/address/logic/parser/EditScheduleCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#109 Change output build jar file name and app title
  build.gradle
  src/main/resources/view/MainWindow.fxml
Labels: type.Chore

#110 Create favourite contact feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/PrefixPresenceUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/parser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FavouriteCommandParser.java
  src/main/java/seedu/address/model/person/Favourite.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.Medium

#120 Unit test edit schedule command
  src/main/java/seedu/address/logic/commands/EditScheduleCommand.java
  src/test/java/seedu/address/logic/commands/EditScheduleCommandTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: type.Chore, type.Bug

#123 Test coverage for meeting-contacts command and parser and delete classes
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/MeetingContactsCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/MeetingContactsCommandTest.java
  src/test/java/seedu/address/logic/parser/MeetingContactsCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetingTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore
